SELECT 'Creating Movies demo schema' AS status;

CREATE TABLE movies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    release_year integer NOT NULL,
    genre varchar(50),
    director varchar(100),
    CONSTRAINT uq_movies_title_release_year UNIQUE (title, release_year)
);

CREATE TABLE actors (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    birth_date date,
    CONSTRAINT uq_actors_name UNIQUE (name)
);

CREATE TABLE movie_actors (
    movie_id integer NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    actor_id integer NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    PRIMARY KEY (movie_id, actor_id)
);

SELECT 'Movies demo schema created' AS status;
